[project]
name = "biomoqa-playground-minimal"
version = "0.1.0"
description = "Minimal version for testing configuration"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "pandas>=2.2.3",
    "numpy>=1.21.0",
    "pathlib2>=2.3.0; python_version < '3.4'",
]
