alpha: 0.616065934327908
direction: max
fold: 4
gamma: 2.274467882881091
hpo_metric: eval_roc_auc
learning_rate: 9.882597067777749e-05
loss_type: focal
model_name: google-bert/bert-base-uncased
nb_optional_negs: 500
num_trials: 25
run_idx: 0
weight_decay: 0.002664109489436967
with_keywords: false
with_title: true
