direction: max
fold: 0
hpo_metric: eval_roc_auc
learning_rate: 3.0378441442185062e-05
loss_type: BCE
model_name: google-bert/bert-base-uncased
nb_optional_negs: 0
num_trials: 25
pos_weight: 0.8178300196637514
run_idx: 0
weight_decay: 1.0426811836320547e-06
with_keywords: false
with_title: true
