direction: max
fold: 4
hpo_metric: eval_roc_auc
learning_rate: 8.325639381650426e-05
loss_type: BCE
model_name: google-bert/bert-base-uncased
nb_optional_negs: 500
num_trials: 25
pos_weight: 1.536290819443697
run_idx: 0
weight_decay: 0.02555006963805325
with_keywords: false
with_title: true
