alpha: 0.43333280187022505
direction: max
fold: 2
gamma: 1.0485915855270356
hpo_metric: eval_roc_auc
learning_rate: 6.877728743793543e-05
loss_type: focal
model_name: google-bert/bert-base-uncased
nb_optional_negs: 500
num_trials: 25
run_idx: 0
weight_decay: 0.0001675569944093657
with_keywords: false
with_title: false
