alpha: 0.5883255649388269
direction: max
fold: 2
gamma: 1.8779527179519286
hpo_metric: eval_roc_auc
learning_rate: 9.804226429301194e-05
loss_type: focal
model_name: dmis-lab/biobert-v1.1
nb_optional_negs: 1000
num_trials: 25
run_idx: 0
weight_decay: 0.09231588333291958
with_keywords: false
with_title: false
