direction: max
fold: 3
hpo_metric: eval_roc_auc
learning_rate: 7.575992927954462e-05
loss_type: BCE
model_name: google-bert/bert-base-uncased
nb_optional_negs: 1000
num_trials: 25
pos_weight: 2.99135153792754
run_idx: 0
weight_decay: 3.805210924495089e-05
with_keywords: false
with_title: false
