alpha: 0.31944725103976734
direction: max
fold: 0
gamma: 0.6905134087360421
hpo_metric: eval_roc_auc
learning_rate: 4.6266224901268155e-05
loss_type: focal
model_name: google-bert/bert-base-uncased
nb_optional_negs: 1000
num_trials: 25
run_idx: 0
weight_decay: 0.00018771771586358846
with_keywords: false
with_title: false
